### ISSUE TITLE
Analyzer picks all path tokens as bucket name except last one

### ISSUE THREAD

**Issue by mnanse** [reportportal/service-auto-analyzer#196]
Hello,

Our QA team wants to enable auto analysis on several projects. Problem is the checkbox is grayed out but the service is running. So the question is, why is this service considered not to be running when it is?

![image](https://github.com/user-attachments/assets/009c3bc0-246b-4120-aa0d-4ceb68ceb151)

![image](https://github.com/user-attachments/assets/ef78144b-1714-41cf-8c00-95bd8fc67959)

I can see sometimes these errors in the logs:

- API Service

```
c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-49 Terms: 
{
    "id": [
        251181,
        251182
    ]
}
 Message: Text '2024-12-04T11:09:26.760615855' could not be parsed, unparsed text found at index 26
```

- Analyzer service

```
2024-12-16 10:42:19,091 - ERROR - analyzerApp.suggestService - InvalidXMLError: message: Invalid XML provided for "ListObjectResult" - erroring tag <IsTruncated>. Message: 'NoneType' object has no attribute 'text'
--
Traceback (most recent call last):
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 101, in get_child_text
return self.element.find('s3:{}'.format(name), _XML_NS).text
AttributeError: 'NoneType' object has no attribute 'text'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/backend/./app/service/suggest_service.py", line 360, in suggest_items
_suggest_decision_maker_to_use = self.model_chooser.choose_model(
File "/backend/./app/commons/model_chooser.py", line 57, in choose_model
folders = self.object_saver.get_folder_objects(project_id, model_name_folder)
File "/backend/./app/commons/object_saving/object_saver.py", line 63, in get_folder_objects
return self.saving_strategy[self.binarystore_type]().get_folder_objects(
File "/backend/./app/commons/object_saving/minio_client.py", line 110, in get_folder_objects
for obj in self.minioClient.list_objects(project_id, prefix=folder):
File "/venv/lib/python3.10/site-packages/minio/api.py", line 2301, in _list_objects
objects, is_truncated, start_after = parse_list_objects(
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 273, in parse_list_objects
is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
File "/venv/lib/python3.10/site-packages/minio/parsers.py", line 103, in get_child_text
raise InvalidXMLError(
minio.error.InvalidXMLError: InvalidXMLError: message: Invalid XML provided for "ListObjectResult" - erroring tag <IsTruncated>. Message: 'NoneType' object has no attribute 'text'
```

But I don't really understand them.

We are running ReportPortal 5.11.0 on AWS ECS. I tried to update to 5.12.0 as suggested in another issue (https://github.com/reportportal/reportportal/issues/2097) but it doesn't help.

I deployed another stack and I get the same issue so maybe it is related to our setup on AWS. If so, Can I know how the service status is checked ?

Thanks !

**Comment by HardNorth** [comment]
@mnanse I don't know, please open a separate issue about this. This one I took for bucket path issue.
