### ISSUE TITLE
extract_message_params AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by jibby0** [reportportal/service-auto-analyzer#34]
Hello all! I'm trying to get auto-analysis up and running for a project.

I see the below error in the analyzer service when:
- Regenerating indexes (clicking "Remove Index" in the project settings auto-analysis page, then "Generate Index").
- Occasionally clicking "Edit Defect Type" on a defect in the associated project.
- Clicking "Analysis" on a test run in the associated project.

```
[2020-08-28 13:44:06,960] [ERROR] [amqp_handler.py:amqp_handler:handle_amqp_request:95] -- Failed to process launches
Traceback (most recent call last):
  File "./amqp/amqp_handler.py", line 93, in handle_amqp_request
    response = request_handler(launches)
  File "./commons/esclient.py", line 171, in index_logs
    bodies.append(self._prepare_log(launch, test_item, log))
  File "./commons/esclient.py", line 311, in _prepare_log
    log_template = self._fill_log_fields(log_template, log, launch.analyzerConfig.numberOfLogLines)
  File "./commons/esclient.py", line 261, in _fill_log_fields
    message_params = " ".join(utils.extract_message_params(detected_message_without_params))
  File "./utils/utils.py", line 453, in extract_message_params
    param = re.search(r"[^\'\"]+", param[1].strip()).group(0).strip()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by MariyaIvanina** [comment]
@jibby0 Hi! I see, this is the bug, it will be fixed in the new version 5.3.1. Sorry for inconvenience!
